### ISSUE TITLE
lb fails to start

### ISSUE THREAD

**Issue by kocic11** [fnproject/fn-helm#22]
Followed the steps to install fn using helm, but getting the following error from lb pod:
panic: unknown (get pods)

goroutine 10 [running]:
github.com/fnproject/fn/fnlb/lb.(*k8sStore).watch(0xc420311110, 0xc420280100, 0x7, 0x7fffdae12744, 0x1b, 0x50)
        /go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:144 +0xb5e
created by github.com/fnproject/fn/fnlb/lb.NewK8sStore
        /go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:56 +0x20e

Please advise.

**Comment by kocic11** [comment]
Setting rbac.enabled to true in fn/values.yaml file fixed the issue.
